# Generated by Django 4.1 on 2022-08-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_foo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foo',
            name='_data',
            field=models.BinaryField(blank=True, db_column='data'),
        ),
    ]
